# Builds the project and publishes the artifacts to GitHub, Modrinth and CurseForge.
# Modrinth publishing requires a Modrinth PAT `MODRINTH_TOKEN`
#   Will skip without error if not present.
# CurseForge publishing requires a CurseForge API token `CURSEFORGE_TOKEN`
#   Will skip without error if not present.
name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        # Common release configurations are listed below: uncomment the one you want to use.
        # Within run commands, release tasks are grouped by loader and ordered by
          # approximate failure probability, highest to lowest.

        # GitHub
          # Fabric
#        run: ./gradlew build fabric:publishGithub --stacktrace
          # Fabric & NeoForge
#        run: ./gradlew build neoforge:publishGithub fabric:publishGithub --stacktrace

        # GitHub & Modrinth
          # Fabric
#        run: ./gradlew build fabric:publishModrinth fabric:publishGithub --stacktrace
          # Fabric & NeoForge
#        run: ./gradlew build neoforge:publishModrinth neoforge:publishGithub fabric:publishModrinth fabric:publishGithub --stacktrace

        # GitHub & Modrinth & CurseForge
          # Fabric
#        run: ./gradlew build fabric:publishModrinth fabric:publishCurseforge fabric:publishGithub --stacktrace
          # Fabric & NeoForge
        run: ./gradlew build neoforge:publishModrinth neoforge:publishCurseforge neoforge:publishGithub fabric:publishModrinth fabric:publishCurseforge fabric:publishGithub --stacktrace

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            **/build/libs/
